---
- name: Update N1 server
  hosts: N1

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir_1
      state: directory


  - name: Create Directory
    file:
      path: /home/centos/new_dir_2
      state: directory

- name: Update N2 server
  hosts: N2

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir_1
      state: directory

  
  - name: Create Directory
    file:
      path: /home/centos/new_dir_2
      state: directory

  - name: Create Directory
    file:
      path: /home/centos/new_dir_3
      state: directory

- name: Update g2 server
  hosts: g2

  tasks:
  - name: Create Directory
    file:
      path: /home/centos/new_dir
      state: directory

...

