---
- name: Install OS
  hosts: g4
  become: yes

  tasks:
    - name: Check OS Distribution
      command: "cat /etc/os-release"
      register: os_release_output

    - name: Install CentOS
      yum:
        name: "{{ 'CentOS 7' }}"
      when: "'CentOS Linux 7 (Core)' in os_release_output.stdout"

    - name: Install Debian
      apt:
        name: "{{ 'Debian 12' }}"
      when: "'Debian GNU/Linux 12 (bookworm)' in os_release_output.stdout"
...