---
- name: Install OS
  hosts: g4
  become: yes

  tasks:
    - name: Check OS Distribution
      command: "cat /etc/os-release"
      register: os_release_output

    - name: Install CentOS
      yum:
        name: "{{ 'centos-release' }}"
      when: "'CentOS Linux 7' in os_release_output.stdout"

    - name: Install Debian
      apt:
        name: sudo
        state: present
      when: os_release_output.stdout is search('Debian')
...